FROM python:3.13-alpine

RUN apk add --no-cache postgresql-client

COPY requirements-updater.txt /tmp/requirements-updater.txt
RUN pip install --no-cache-dir -r /tmp/requirements-updater.txt

WORKDIR /opt/updater
COPY deployment_agent.py .

ENV PYTHONUNBUFFERED=1

EXPOSE 8080
CMD ["python", "deployment_agent.py"]
