# Generated by Django 5.2.14 on 2026-05-21 15:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='foerdersatz',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.5000'), help_text='0 bis 1, zum Beispiel 0,5000 fuer 50 Prozent.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='charge',
            name='foerderfaehig',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drinkentry',
            name='foerderfaehig',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mealsignup',
            name='foerderfaehig',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='berufssatz',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='0 bis 1, zum Beispiel 0,3300.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='participant',
            name='hilfssatz',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='0 bis 1, zum Beispiel 0,5000.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='foerderfaehig',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='camp_flat_duration',
            field=models.CharField(blank=True, choices=[('1w', '1 Woche'), ('2w', '2 Wochen')], max_length=2),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='camp_flat_role',
            field=models.CharField(blank=True, choices=[('participant', 'Teilnehmer'), ('companion', 'Begleitperson')], max_length=20),
        ),
    ]
