# Generated by Django 5.2.14 on 2026-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_repair_pricerule_camp_flat_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerule',
            name='applies_to_companions',
            field=models.BooleanField(default=True),
        ),
    ]
