# Generated by Django 5.2.14 on 2026-05-22 11:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_settlement_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='foerdersatz',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.5000'), help_text='0 bis 1, zum Beispiel 0,5000 fuer 50 Prozent. Dies bestimmt den allgemeinen Zuschuss.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='berufssatz',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='0 bis 1, zum Beispiel 0,3300. Der Berufssatz reduziert die Kosten basierend auf dem Status.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='hilfssatz',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='0 bis 1, zum Beispiel 0,5000. Der Hilfssatz reduziert die Kosten des Teilnehmers.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
    ]
