# Generated by Django 5.2.14 on 2026-06-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_pricerule_applies_to_companions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerule',
            name='meal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Frühstück'), ('lunch', 'Mittagessen'), ('dinner', 'Abendessen')], max_length=20),
        ),
    ]
