# Generated by Django 5.2.14 on 2026-05-22 12:48

import django.db.models.deletion
from django.db import migrations, models


def _participant_duration(price_rule_model, participant):
    nights = participant.actual_nights or participant.booked_nights or 0
    if nights > 7:
        return "2w"
    return "1w"


def _participant_role(price_rule_model, participant):
    if participant.is_companion:
        return "companion"
    return "participant"


def backfill_overnight_categories(apps, schema_editor):
    Camp = apps.get_model("billing", "Camp")
    OvernightCategory = apps.get_model("billing", "OvernightCategory")
    Participant = apps.get_model("billing", "Participant")
    PriceRule = apps.get_model("billing", "PriceRule")

    category_labels = {
        ("participant", "1w"): "Teilnehmer 1 Woche",
        ("participant", "2w"): "Teilnehmer 2 Wochen",
        ("companion", "1w"): "Begleitperson 1 Woche",
        ("companion", "2w"): "Begleitperson 2 Wochen",
    }

    for camp in Camp.objects.all():
        categories = {}

        for rule in PriceRule.objects.filter(camp=camp, kind="camp_flat"):
            key = (rule.camp_flat_role, rule.camp_flat_duration)
            label = category_labels.get(key, "Bestand")
            category, _ = OvernightCategory.objects.get_or_create(camp=camp, name=label)
            categories[key] = category
            if not rule.overnight_category_id:
                rule.overnight_category = category
                rule.save(update_fields=["overnight_category"])

        fallback_category, _ = OvernightCategory.objects.get_or_create(
            camp=camp,
            name="Bestand",
            defaults={"description": "Automatisch aus vorhandenen Daten erzeugt."},
        )

        for participant in Participant.objects.filter(camp=camp, overnight_category__isnull=True):
            key = (_participant_role(PriceRule, participant), _participant_duration(PriceRule, participant))
            participant.overnight_category = categories.get(key, fallback_category)
            participant.save(update_fields=["overnight_category"])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_camp_foerdersatz_alter_participant_berufssatz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='primary_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_participants', to='billing.participant'),
        ),
        migrations.CreateModel(
            name='OvernightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overnight_categories', to='billing.camp')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='overnight_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='billing.overnightcategory'),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='overnight_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_rules', to='billing.overnightcategory'),
        ),
        migrations.RunPython(backfill_overnight_categories, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='overnightcategory',
            constraint=models.UniqueConstraint(fields=('camp', 'name'), name='unique_overnight_category_name_per_camp'),
        ),
    ]
