# Generated by Django 5.2.14 on 2026-06-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_pricerule_meal_date_pricerule_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealsignup',
            name='meal',
            field=models.CharField(choices=[('breakfast', 'Frühstück'), ('dinner', 'Abendessen')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Frühstück'), ('dinner', 'Abendessen')], max_length=20),
        ),
    ]
