# Generated by Codex on 2026-06-03

from django.db import migrations, models
import django.db.models.deletion


def populate_audit_log_participants(apps, schema_editor):
    BookingAuditLog = apps.get_model("billing", "BookingAuditLog")
    for audit_log in BookingAuditLog.objects.select_related("charge").filter(participant__isnull=True):
        if audit_log.charge_id is None:
            continue
        audit_log.participant_id = audit_log.charge.participant_id
        audit_log.save(update_fields=["participant"])


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_bookingauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingauditlog",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_audit_logs",
                to="billing.participant",
            ),
        ),
        migrations.RunPython(populate_audit_log_participants, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="bookingauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("updated", "Bearbeitet"),
                    ("deleted", "Gelöscht"),
                    ("restored", "Wiederhergestellt"),
                ],
                default="updated",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookingauditlog",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="billing.charge",
            ),
        ),
    ]
