# Generated by Django 5.2.14 on 2026-06-03 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_bookingauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='cancellation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charge',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealsignup',
            name='cancellation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mealsignup',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealsignup',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_meal_signups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealsignup',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingauditlog',
            name='action',
            field=models.CharField(choices=[('updated', 'Bearbeitet'), ('cancelled', 'Storniert'), ('restored', 'Storno zurückgenommen')], default='updated', max_length=20),
        ),
    ]
