# Generated by Django 5.2.14 on 2026-06-04 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_charge_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantBookingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt'), ('revoked', 'Aufgelöst')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('child', 'Kind'), ('companion', 'Begleitperson')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='mealsignup',
            name='unique_meal_signup',
        ),
        migrations.AddField(
            model_name='participantbookinglink',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_booking_links', to='billing.participant'),
        ),
        migrations.AddField(
            model_name='participantbookinglink',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_booking_links', to='billing.participant'),
        ),
        migrations.AddField(
            model_name='participantfamilymember',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='billing.participant'),
        ),
        migrations.AddField(
            model_name='mealsignup',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_signups', to='billing.participantfamilymember'),
        ),
        migrations.AddConstraint(
            model_name='mealsignup',
            constraint=models.UniqueConstraint(condition=models.Q(('family_member__isnull', True)), fields=('participant', 'meal_date', 'meal'), name='unique_meal_signup'),
        ),
        migrations.AddConstraint(
            model_name='mealsignup',
            constraint=models.UniqueConstraint(condition=models.Q(('family_member__isnull', False)), fields=('participant', 'family_member', 'meal_date', 'meal'), name='unique_family_member_meal_signup'),
        ),
        migrations.AddConstraint(
            model_name='participantbookinglink',
            constraint=models.CheckConstraint(condition=models.Q(('inviter', models.F('invitee')), _negated=True), name='booking_link_distinct_participants'),
        ),
    ]
