# Generated by Django 5.2.14 on 2026-06-04 15:03

import datetime

import django.db.models.deletion
from django.db import migrations, models


def link_existing_meal_charges(apps, schema_editor):
    MealSignup = apps.get_model("billing", "MealSignup")
    Charge = apps.get_model("billing", "Charge")
    meal_labels = {"breakfast": "Frühstück", "dinner": "Abendessen"}
    for signup in MealSignup.objects.select_related("family_member").filter(charge__isnull=True):
        meal_label = meal_labels.get(signup.meal, "")
        charges = Charge.objects.filter(
            participant_id=signup.participant_id,
            kind="food",
            occurred_on=signup.meal_date,
            deleted_at__isnull=True,
        )
        if meal_label:
            charges = charges.filter(description__contains=meal_label)
        if signup.family_member_id is not None:
            family_name = f"{signup.family_member.first_name} {signup.family_member.last_name}".strip()
            charges = charges.filter(description__contains=family_name)
        charge = charges.order_by("pk").first()
        if charge is not None:
            signup.charge_id = charge.pk
            signup.save(update_fields=["charge"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_participantbookinglink_participantfamilymember_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="meal_booking_cutoff_time",
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name="mealsignup",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meal_signups",
                to="billing.charge",
            ),
        ),
        migrations.AddField(
            model_name="mealsignup",
            name="retracted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mealsignup",
            name="status",
            field=models.CharField(
                choices=[("active", "Gebucht"), ("retracted", "Zurückgenommen")], default="active", max_length=20
            ),
        ),
        migrations.RunPython(link_existing_meal_charges, migrations.RunPython.noop),
    ]
