# Generated by Django 5.2.14 on 2026-06-05 14:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_camp_meal_booking_cutoff_time_mealsignup_charge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_date', models.DateField()),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_orders', to='billing.camp')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_meal_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meal_date'],
                'constraints': [models.UniqueConstraint(fields=('camp', 'meal_date'), name='unique_meal_order_per_camp_date')],
            },
        ),
    ]
