# Generated by Django 5.2.14 on 2026-06-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_userprofile'),
        ('billing', '0014_subsidy_rate_per_price_element'),
    ]

    operations = [
    ]
