# Generated by Django 5.2.14 on 2026-06-08 17:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_merge_20260608_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='shift_ratio_per_night',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Anzahl benötigter Dienste pro gebuchter Nacht, z.B. 0.2 für 1 Dienst pro 5 Nächte.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('required_slots', models.PositiveIntegerField(default=1)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='billing.camp')),
            ],
            options={
                'ordering': ['date', 'start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='billing.participant')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='billing.shift')),
            ],
            options={
                'ordering': ['shift', 'participant'],
                'constraints': [models.UniqueConstraint(fields=('shift', 'participant'), name='unique_shift_assignment')],
            },
        ),
    ]
