# Generated by Django 5.2.14 on 2026-06-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_participantpin_login_lockout'),
        ('billing', '0016_camp_shift_ratio_per_night_shift_shiftassignment'),
    ]

    operations = [
    ]
