# Generated by Django 5.2.14 on 2026-06-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_merge_20260608_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='offered_for_exchange',
            field=models.BooleanField(default=False),
        ),
    ]
