# Generated by Django 5.2.14 on 2026-06-08 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_shiftassignment_offered_for_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('required_slots', models.PositiveIntegerField(default=1)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_shift_templates', to='billing.camp')),
            ],
            options={
                'ordering': ['start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyShiftException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('is_skipped', models.BooleanField(default=False)),
                ('custom_required_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_start_time', models.TimeField(blank=True, null=True)),
                ('custom_end_time', models.TimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='billing.dailyshifttemplate')),
            ],
            options={
                'ordering': ['date', 'template'],
                'constraints': [models.UniqueConstraint(fields=('template', 'date'), name='unique_shift_exception')],
            },
        ),
    ]
