# Generated by Django 5.2.14 on 2026-06-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_settlementrun_versioned_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealsignup',
            name='variant',
            field=models.CharField(choices=[('normal', 'Mit Fleisch'), ('vegan', 'Vegan'), ('normal_child', 'Mit Fleisch Kind'), ('vegan_child', 'Vegan Kind')], max_length=20),
        ),
    ]
