# Generated by Django 5.2.14 on 2026-06-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_alter_mealsignup_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='iban',
            field=models.CharField(blank=True, help_text='IBAN für Überweisungen', max_length=40),
        ),
        migrations.AddField(
            model_name='camp',
            name='paypal_link',
            field=models.CharField(blank=True, help_text='PayPal.me Link oder E-Mail-Adresse', max_length=200),
        ),
    ]
