# Generated by Django 5.2.14 on 2026-06-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_camp_iban_camp_paypal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
