# Generated by Django 5.2.14 on 2026-06-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_expense_allocation_method_expense_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Rechnungsbeleg'),
        ),
    ]
