# Generated by Django 5.2.14 on 2026-06-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_expense_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Begründung der Ablehnung, sichtbar für den Teilnehmer.'),
        ),
    ]
