# Generated by Django 5.2.14 on 2026-06-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_expense_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cost_center',
            field=models.CharField(blank=True, choices=[('food_breakfast', 'Unterkunft/Verpflegung - Frühstück'), ('food_dinner', 'Unterkunft/Verpflegung - Abendessen'), ('food_other', 'Unterkunft/Verpflegung - Sonstiges'), ('travel', 'Fahrtkosten'), ('materials', 'Verbrauchsmaterial'), ('rent_other', 'Miete/sonstiges')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='allocation_method',
            field=models.CharField(choices=[('none', 'Nicht umlegen'), ('cost_center', 'Auf Kostenstelle umlegen'), ('all_active', 'Alle aktiven Teilnehmer'), ('selected', 'Ausgewählte Teilnehmer')], default='none', max_length=20),
        ),
    ]
