# Generated by Django 6.0.6 on 2026-06-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_settlementrun_cost_center_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerule',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Frühstück'), ('dinner', 'Abendessen'), ('snack', 'Mittagssnack')], max_length=20),
        ),
    ]
