# Generated by Django 6.0.6 on 2026-06-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_settlementrun_cost_center_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='kind',
            field=models.CharField(choices=[('camp_flat', 'Lagerpauschale'), ('food', 'Verpflegung'), ('drink', 'Getränke'), ('snack', 'Snack/Schnellverpflegung'), ('other', 'Sonstige Kosten')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='kind',
            field=models.CharField(choices=[('camp_flat', 'Lagerpauschale'), ('night', 'Übernachtung'), ('meal', 'Verpflegung'), ('drink', 'Getränk'), ('snack', 'Snack/Schnellverpflegung'), ('other', 'Sonstiges')], max_length=20),
        ),
    ]
