# Generated by Django 6.0.6 on 2026-06-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_alter_pricerule_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerule',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
