# Generated by Django 6.0.6 on 2026-07-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_daily_settlement_backups'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantfamilymember',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantfamilymember',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
