# Generated by Django 6.0.6 on 2026-07-08 19:28

import django.db.models.deletion
from django.db import migrations, models


def create_companion_pins(apps, schema_editor):
    ParticipantFamilyMember = apps.get_model('billing', 'ParticipantFamilyMember')
    ParticipantFamilyMemberPin = apps.get_model('billing', 'ParticipantFamilyMemberPin')
    companion_ids = ParticipantFamilyMember.objects.filter(role='companion').values_list('pk', flat=True)
    existing_ids = set(
        ParticipantFamilyMemberPin.objects.filter(family_member_id__in=companion_ids).values_list(
            'family_member_id',
            flat=True,
        )
    )
    ParticipantFamilyMemberPin.objects.bulk_create(
        [
            ParticipantFamilyMemberPin(family_member_id=family_member_id)
            for family_member_id in companion_ids
            if family_member_id not in existing_ids
        ]
    )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_family_member_travel_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantFamilyMemberPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pin_hash', models.CharField(blank=True, max_length=256)),
                ('must_set_pin', models.BooleanField(default=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('family_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin', to='billing.participantfamilymember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_companion_pins, noop_reverse),
    ]
