# Generated by Django 6.0.6 on 2026-07-20 12:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_passkey_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.URLField(max_length=2048, unique=True)),
                ('p256dh', models.CharField(max_length=512)),
                ('auth', models.CharField(max_length=512)),
                ('device_name', models.CharField(default='Dieses Gerät', max_length=80)),
                ('categories', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='billing.participant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['device_name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=300)),
                ('target_url', models.CharField(max_length=500)),
                ('dedupe_key', models.CharField(max_length=180)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=40)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='billing.pushsubscription')),
            ],
            options={
                'ordering': ['scheduled_for', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='pushsubscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('participant__isnull', True), ('user__isnull', False)), models.Q(('participant__isnull', False), ('user__isnull', True)), _connector='OR'), name='push_subscription_exactly_one_owner'),
        ),
        migrations.AddIndex(
            model_name='pushmessage',
            index=models.Index(fields=['status', 'next_attempt_at'], name='push_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushmessage',
            constraint=models.UniqueConstraint(fields=('subscription', 'dedupe_key'), name='unique_push_message_dedupe'),
        ),
    ]
