# Generated by Django 6.0.6 on 2026-07-23 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0038_push_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('information', 'Information'), ('settlement', 'Rechnung')], max_length=20)),
                ('subject', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='email_batches', to='billing.camp')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_batches', to=settings.AUTH_USER_MODEL)),
                ('settlement_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='email_batches', to='billing.settlementrun')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=254)),
                ('password_encrypted', models.TextField(blank=True)),
                ('security', models.CharField(choices=[('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS')], default='starttls', max_length=20)),
                ('from_name', models.CharField(blank=True, max_length=160)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('timeout', models.PositiveSmallIntegerField(default=10)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_email_configurations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_email_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-Mail-Konfiguration',
                'verbose_name_plural': 'E-Mail-Konfigurationen',
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_names', models.JSONField(default=list)),
                ('dedupe_key', models.CharField(max_length=180)),
                ('subject', models.CharField(max_length=160)),
                ('body_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('processing', 'In Verarbeitung'), ('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=40)),
                ('attachment_sha256', models.CharField(blank=True, max_length=64)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='billing.emailbatch')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='email_deliveries', to='billing.settlement')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EmailTestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('success', 'Erfolgreich'), ('failed', 'Fehlgeschlagen')], max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_test_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='emailbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'information'), ('settlement_run__isnull', True)), models.Q(('kind', 'settlement'), ('settlement_run__isnull', False)), _connector='OR'), name='email_batch_run_matches_kind'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='email_delivery_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='emaildelivery',
            constraint=models.UniqueConstraint(fields=('batch', 'dedupe_key'), name='unique_email_delivery_dedupe'),
        ),
    ]
