# Generated by Django 6.0.7 on 2026-07-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0040_campannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='show_kiosk_invoices',
            field=models.BooleanField(default=True, help_text='Steuert, ob Teilnehmer ihre Abrechnungen im Kiosk einsehen und herunterladen können.'),
        ),
    ]
