# Generated by Django 6.0.7 on 2026-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0041_camp_show_kiosk_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Ausstehende Freigabe'), ('registered', 'Angemeldet'), ('active', 'Aktiv'), ('settled', 'Abgerechnet'), ('cancelled', 'Storniert')], default='registered', max_length=20),
        ),
    ]
