# Generated by Django 6.0.7 on 2026-07-29 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0044_campkioskaccessattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampKioskRegistrationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_key", models.CharField(max_length=64)),
                ("attempt_timestamps", models.JSONField(default=list)),
                (
                    "access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_attempt_states",
                        to="billing.campkioskaccess",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["updated_at"],
                        name="kiosk_reg_attempt_updated_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("access", "client_key"),
                        name="unique_kiosk_reg_attempt_client",
                    )
                ],
            },
        ),
    ]
