# Generated by Django 6.0.7 on 2026-07-29 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0045_campkioskregistrationattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="KioskActionAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("link_invited", "Partner eingeladen"),
                            ("link_accepted", "Partnerfreigabe angenommen"),
                            ("link_declined", "Partnerfreigabe abgelehnt"),
                            ("link_revoked", "Partnerfreigabe widerrufen"),
                            ("quick_booked", "Schnellbuchung erstellt"),
                            ("quick_cancelled", "Schnellbuchung storniert"),
                            ("meal_booked", "Essensanmeldung gespeichert"),
                            ("meal_retracted", "Essensanmeldung zurückgenommen"),
                            ("checkin_updated", "Anwesenheit geändert"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_family_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_kiosk_action_audit_logs",
                        to="billing.participantfamilymember",
                    ),
                ),
                (
                    "actor_participant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_kiosk_action_audit_logs",
                        to="billing.participant",
                    ),
                ),
                (
                    "booking_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kiosk_action_audit_logs",
                        to="billing.participantbookinglink",
                    ),
                ),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kiosk_action_audit_logs",
                        to="billing.camp",
                    ),
                ),
                (
                    "charge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kiosk_action_audit_logs",
                        to="billing.charge",
                    ),
                ),
                (
                    "target_family_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_kiosk_action_audit_logs",
                        to="billing.participantfamilymember",
                    ),
                ),
                (
                    "target_participant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_kiosk_action_audit_logs",
                        to="billing.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["camp", "-created_at"], name="kiosk_audit_camp_created"),
                    models.Index(fields=["actor_participant", "-created_at"], name="kiosk_audit_actor_created"),
                    models.Index(fields=["target_participant", "-created_at"], name="kiosk_audit_target_created"),
                ],
            },
        ),
    ]
