# Generated by Django 6.0.7 on 2026-07-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0046_kiosk_action_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="kiosk_confirmation_nonce",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Einmaliger Marker der kostenpflichtig bestätigten Kiosk-Mehrfachbuchung.",
                null=True,
                unique=True,
            ),
        ),
    ]
