# Generated by Django 6.0.7 on 2026-07-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0047_charge_kiosk_confirmation_nonce"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealsignup",
            name="retraction_version",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
