# Generated by Django 6.0.7 on 2026-07-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0051_remove_booking_link_mutation_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_key', models.CharField(max_length=256, unique=True)),
                ('failure_timestamps', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
