# Generated by Django 6.0.7 on 2026-08-06 13:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0052_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='berufssatz',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='0 bis 1, zum Beispiel 0,3300.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='hilfssatz',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='0 bis 1, zum Beispiel 0,5000.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
    ]
