# Generated by Django 6.0.7 on 2026-08-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0053_participant_subsidy_rate_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='kind',
            field=models.CharField(choices=[('camp_flat', 'Lagerpauschale'), ('food', 'Verpflegung'), ('drink', 'Getränke'), ('other', 'Sonstige Kosten'), ('donation', 'Spende')], max_length=20),
        ),
    ]
