# Generated by Django 6.0.7 on 2026-08-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0054_alter_charge_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerule',
            name='kind',
            field=models.CharField(choices=[('camp_flat', 'Lagerpauschale'), ('night', 'Übernachtung'), ('meal', 'Verpflegung'), ('drink', 'Getränk'), ('other', 'Sonstiges'), ('donation', 'Spende')], max_length=20),
        ),
    ]
