# Generated by Django 6.0.7 on 2026-08-14 14:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0059_participantfamilymember_is_youth_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camp",
            options={"ordering": ["-year", "name"], "verbose_name": "Lager", "verbose_name_plural": "Lager"},
        ),
        migrations.AlterModelOptions(
            name="dailyshifttemplate",
            options={
                "ordering": ["start_time", "name"],
                "verbose_name": "Dienstvorlage",
                "verbose_name_plural": "Dienstvorlagen",
            },
        ),
        migrations.AlterModelOptions(
            name="mealorder",
            options={
                "ordering": ["-meal_date"],
                "verbose_name": "Essensbestellung",
                "verbose_name_plural": "Essensbestellungen",
            },
        ),
        migrations.AlterModelOptions(
            name="mealplanentry",
            options={
                "ordering": ["meal_date", "meal"],
                "verbose_name": "Speiseplan",
                "verbose_name_plural": "Speisepläne",
            },
        ),
        migrations.AlterModelOptions(
            name="mealsignup",
            options={
                "ordering": ["meal_date", "meal", "participant"],
                "verbose_name": "Essensanmeldung",
                "verbose_name_plural": "Essensanmeldungen",
            },
        ),
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Teilnehmer",
                "verbose_name_plural": "Teilnehmer",
            },
        ),
        migrations.AlterModelOptions(
            name="pricerule",
            options={"ordering": ["kind", "name"], "verbose_name": "Preisregel", "verbose_name_plural": "Preisregeln"},
        ),
        migrations.AlterModelOptions(
            name="shift",
            options={
                "ordering": ["date", "start_time", "name"],
                "verbose_name": "Dienst",
                "verbose_name_plural": "Dienste",
            },
        ),
        migrations.AlterField(
            model_name="mealorder",
            name="camp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_orders",
                to="billing.camp",
                verbose_name="Lager",
            ),
        ),
        migrations.AlterField(
            model_name="mealorder",
            name="meal_date",
            field=models.DateField(verbose_name="Mahlzeitentag"),
        ),
        migrations.AlterField(
            model_name="mealorder",
            name="ordered_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Bestellt am"),
        ),
        migrations.AlterField(
            model_name="mealorder",
            name="ordered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_meal_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bestellt von",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="actual_nights",
            field=models.PositiveIntegerField(default=0, verbose_name="Tatsächliche Nächte"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="berufssatz",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="0 bis 1, zum Beispiel 0,3300.",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="Berufssatz",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="camp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="billing.camp",
                verbose_name="Lager",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-Mail-Adresse"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="first_name",
            field=models.CharField(max_length=120, verbose_name="Vorname"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="hilfssatz",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="0 bis 1, zum Beispiel 0,5000.",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="Hilfssatz",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="is_child",
            field=models.BooleanField(default=False, verbose_name="Kind"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="is_companion",
            field=models.BooleanField(default=False, verbose_name="Begleitperson"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="is_youth_group",
            field=models.BooleanField(default=False, verbose_name="Jugendgruppe"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="last_name",
            field=models.CharField(max_length=120, verbose_name="Nachname"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="phone",
            field=models.CharField(blank=True, max_length=80, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Ausstehende Freigabe"),
                    ("registered", "Angemeldet"),
                    ("active", "Aktiv"),
                    ("settled", "Abgerechnet"),
                    ("cancelled", "Storniert"),
                ],
                default="registered",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="camp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="billing.camp",
                verbose_name="Lager",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="date",
            field=models.DateField(verbose_name="Datum"),
        ),
        migrations.AlterField(
            model_name="shift",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Ende"),
        ),
        migrations.AlterField(
            model_name="shift",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Bezeichnung"),
        ),
        migrations.AlterField(
            model_name="shift",
            name="required_slots",
            field=models.PositiveIntegerField(default=1, verbose_name="Benötigte Plätze"),
        ),
        migrations.AlterField(
            model_name="shift",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Beginn"),
        ),
    ]
