# Generated by Django 6.0.8 on 2026-08-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0061_meal_booking_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyshifttemplate",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="shift",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
