# Generated by Django 6.0.8 on 2026-08-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("billing", "0062_shift_descriptions")]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="attendance_tracking_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="participant",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participantfamilymember",
            name="attendance_tracking_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="participantfamilymember",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participantfamilymember",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="participantfamilymember",
            name="phone",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="kioskactionauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("link_invited", "Partner eingeladen"),
                    ("link_accepted", "Partnerfreigabe angenommen"),
                    ("link_declined", "Partnerfreigabe abgelehnt"),
                    ("link_revoked", "Partnerfreigabe widerrufen"),
                    ("quick_booked", "Schnellbuchung erstellt"),
                    ("quick_cancelled", "Schnellbuchung storniert"),
                    ("meal_booked", "Essensanmeldung gespeichert"),
                    ("meal_retracted", "Essensanmeldung zurückgenommen"),
                    ("checkin_updated", "Anwesenheit geändert"),
                    ("profile_updated", "Stammdaten geändert"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AttendanceDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("is_present", models.BooleanField(default=False)),
                ("comment", models.CharField(blank=True, max_length=500)),
                (
                    "family_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_days",
                        to="billing.participantfamilymember",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_days",
                        to="billing.participant",
                    ),
                ),
            ],
            options={"ordering": ["date", "pk"]},
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.UniqueConstraint(
                condition=models.Q(("family_member__isnull", True)),
                fields=("participant", "date"),
                name="unique_participant_attendance_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.UniqueConstraint(
                condition=models.Q(("family_member__isnull", False)),
                fields=("family_member", "date"),
                name="unique_family_attendance_day",
            ),
        ),
    ]
