# Generated by Django 6.0.7 on 2026-08-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0063_attendance_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="attendance_tracking_enabled",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="participantfamilymember",
            name="attendance_tracking_enabled",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
