# Generated by Django 6.0.8 on 2026-08-18 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0064_make_attendance_tracking_internal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('deleted', 'Gelöscht'), ('restored', 'Wiederhergestellt')], default='deleted', max_length=20)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['participant', 'deleted_at'], name='payment_participant_active'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_logs', to='billing.participant'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='billing.payment'),
        ),
    ]
