# Generated by Django 6.1 on 2026-08-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0068_charge_position_report_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="kiosk_confirmation_nonce",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Einmaliger Idempotenzmarker für eine Kiosk-Schnellbuchung.",
                null=True,
                unique=True,
            ),
        ),
    ]
