# Generated by Django 6.1 on 2026-08-25 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0070_alter_camp_options_alter_dailyshifttemplate_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="ends_on",
            field=models.DateField(blank=True, null=True, verbose_name="Ende"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="meal_booking_cutoff_time",
            field=models.TimeField(default=datetime.time(12, 0), verbose_name="Anmeldeschluss für Essen"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="starts_on",
            field=models.DateField(blank=True, null=True, verbose_name="Beginn"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="year",
            field=models.PositiveIntegerField(verbose_name="Jahr"),
        ),
    ]
