# Generated by Django 6.1 on 2026-09-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0072_shift_staffing_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='meal_order_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Erinnert Admins, Bearbeiter und Hübers an die offene Caterer-Bestellung.', verbose_name='Bestellhinweise für das Essensteam'),
        ),
        migrations.AddField(
            model_name='camp',
            name='meal_participant_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Erinnert Teilnehmer vor der Richtzeit daran, das Abendessen für morgen zu prüfen.', verbose_name='Teilnehmer-Erinnerungen zur Essensbuchung'),
        ),
    ]
