# Generated by Django 6.1 on 2026-09-09 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0074_account_recovery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pushsubscription',
            name='push_subscription_exactly_one_owner',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='billing.participantfamilymember'),
        ),
        migrations.AddConstraint(
            model_name='pushsubscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('family_member__isnull', True), ('participant__isnull', True), ('user__isnull', False)), models.Q(('family_member__isnull', True), ('participant__isnull', False), ('user__isnull', True)), models.Q(('family_member__isnull', False), ('participant__isnull', True), ('user__isnull', True)), _connector='OR'), name='push_subscription_exactly_one_owner'),
        ),
    ]
