# Generated by Django 6.1 on 2026-09-09 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_companion_subscriptions_on_reverse(apps, schema_editor):
    """Remove subscriptions whose owner cannot be represented by the previous schema."""
    PushSubscription = apps.get_model('billing', 'PushSubscription')
    PushSubscription.objects.using(schema_editor.connection.alias).filter(
        family_member_id__isnull=False,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0074_account_recovery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pushsubscription',
            name='push_subscription_exactly_one_owner',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='billing.participantfamilymember'),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=remove_companion_subscriptions_on_reverse,
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='identity_verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='identity_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='pushsubscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('family_member__isnull', True), ('participant__isnull', True), ('user__isnull', False)), models.Q(('family_member__isnull', True), ('participant__isnull', False), ('user__isnull', True)), models.Q(('family_member__isnull', False), ('participant__isnull', True), ('user__isnull', True)), _connector='OR'), name='push_subscription_exactly_one_owner'),
        ),
    ]
