# Generated by Django 6.1 on 2026-09-10

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.db import migrations, models
from django.utils import timezone
from django.utils.crypto import salted_hmac


def bind_existing_email_recovery_tokens(apps, schema_editor):
    """Derive legacy delivery channels from their persisted outbox relationships."""
    AccountRecoveryToken = apps.get_model("billing", "AccountRecoveryToken")
    email_tokens = AccountRecoveryToken.objects.filter(email_deliveries__isnull=False).distinct()
    for recovery in email_tokens.iterator():
        recipients = set()
        for recipient in recovery.email_deliveries.values_list("recipient_email", flat=True):
            normalized = recipient.strip().casefold()
            try:
                validate_email(normalized)
            except ValidationError:
                continue
            recipients.add(normalized)
        ambiguous = len(recipients) != 1 or recovery.push_messages.exists()
        if ambiguous:
            recovery.used_at = recovery.used_at or timezone.now()
            recovery.token_digest = None
            recovery.expires_at = None
            recovery.save(update_fields=["used_at", "token_digest", "expires_at", "updated_at"])
            continue
        recipient_digest = salted_hmac(
            "billing.account-recovery-recipient",
            recipients.pop(),
            secret=settings.SECRET_KEY,
            algorithm="sha256",
        ).hexdigest()
        recovery.delivery_channel = "email"
        recovery.recipient_email_digest = recipient_digest
        recovery.save(update_fields=["delivery_channel", "recipient_email_digest", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [("billing", "0075_remove_pushsubscription_push_subscription_exactly_one_owner_and_more")]

    operations = [
        migrations.AddField(
            model_name="accountrecoverytoken",
            name="delivery_channel",
            field=models.CharField(choices=[("email", "E-Mail"), ("push", "Push")], default="push", max_length=8),
        ),
        migrations.AddField(
            model_name="accountrecoverytoken",
            name="recipient_email_digest",
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.RunPython(bind_existing_email_recovery_tokens, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="accountrecoverytoken",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("delivery_channel", "email"), ("recipient_email_digest__isnull", False))
                    | models.Q(("delivery_channel", "push"), ("recipient_email_digest__isnull", True))
                ),
                name="recovery_token_delivery_binding_matches_channel",
            ),
        ),
    ]
