# Generated by Django 6.1 on 2026-09-10 17:43

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def invalidate_unbound_delivered_push_tokens(apps, schema_editor):
    """Fail closed for push links issued before an exact device was persisted."""
    AccountRecoveryToken = apps.get_model("billing", "AccountRecoveryToken")
    AccountRecoveryToken.objects.using(schema_editor.connection.alias).filter(
        delivery_channel="push", used_at__isnull=True, token_digest__isnull=False
    ).update(used_at=timezone.now(), token_digest=None, expires_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0077_accountrecoveryidentifierattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountrecoverytoken",
            name="delivery_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivered_account_recovery_tokens",
                to="billing.pushsubscription",
            ),
        ),
        migrations.RunPython(invalidate_unbound_delivered_push_tokens, migrations.RunPython.noop),
    ]
