# Generated by Django 6.1 on 2026-09-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0078_recovery_push_delivery_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountrecoverytoken",
            name="push_delivery_bound",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
