# Generated by Django 6.1 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("billing", "0079_recovery_push_delivery_bound")]

    operations = [
        migrations.CreateModel(
            name="AccountRecoveryDeliveryRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier", models.CharField(max_length=254)),
                ("origin", models.URLField(max_length=500)),
                ("status", models.CharField(choices=[("pending", "Ausstehend"), ("processing", "In Verarbeitung"), ("sent", "Eingeplant"), ("failed", "Fehlgeschlagen")], default="pending", max_length=20)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=40)),
            ],
            options={"indexes": [models.Index(fields=["status", "created_at"], name="recovery_request_due_idx")]},
        )
    ]
