# Generated by Django 6.1 on 2026-09-12

from django.db import migrations, models
from django.utils import timezone


def invalidate_active_kiosk_tokens(apps, schema_editor):
    """Invalidate kiosk bearers before removing their route binding."""
    AccountRecoveryToken = apps.get_model("billing", "AccountRecoveryToken")
    AccountRecoveryToken.objects.using(schema_editor.connection.alias).filter(
        kind__in=("participant_pin", "family_member_pin"),
        used_at__isnull=True,
        token_digest__isnull=False,
    ).update(used_at=timezone.now(), token_digest=None, expires_at=None)


class Migration(migrations.Migration):
    dependencies = [("billing", "0080_accountrecoverydeliveryrequest")]

    operations = [
        migrations.AddField(
            model_name="accountrecoverytoken",
            name="kiosk_mode",
            field=models.CharField(
                blank=True,
                choices=[("private", "Privater Kiosk"), ("central", "Zentraler Kiosk")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, invalidate_active_kiosk_tokens),
    ]
