# Generated by Django 6.1 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("billing", "0080_accountrecoverydeliveryrequest")]

    operations = [
        migrations.AddField(
            model_name="accountrecoverytoken",
            name="kiosk_mode",
            field=models.CharField(
                blank=True,
                choices=[("private", "Privater Kiosk"), ("central", "Zentraler Kiosk")],
                max_length=8,
                null=True,
            ),
        ),
    ]
