from django.urls import path

from . import views

urlpatterns = [
    path("setup/", views.setup_first_admin, name="setup"),
    path("users/", views.user_list, name="user-list"),
    path("users/new/", views.user_create, name="user-create"),
    path("users/<int:user_id>/edit/", views.user_edit, name="user-edit"),
    path("users/<int:user_id>/password/", views.user_password_reset, name="user-password-reset"),
    path("", views.kiosk_home, name="kiosk-root"),
    path("camps/", views.camp_list, name="camp-list"),
    path("camps/new/", views.camp_create, name="camp-create"),
    path("camps/<int:camp_id>/", views.camp_detail, name="camp-detail"),
    path("camps/<int:camp_id>/edit/", views.camp_edit, name="camp-edit"),
    path("camps/<int:camp_id>/meals/", views.camp_meal_overview, name="camp-meal-overview"),
    path("camps/<int:camp_id>/meals/cutoff/", views.meal_cutoff_edit, name="meal-cutoff-edit"),
    path("camps/<int:camp_id>/meals/order-sent/", views.meal_order_mark_sent, name="meal-order-mark-sent"),
    path("camps/<int:camp_id>/participants/new/", views.participant_create, name="participant-create"),
    path("participants/<int:participant_id>/", views.participant_detail, name="participant-detail"),
    path("participants/<int:participant_id>/charges/new/", views.charge_create, name="charge-create"),
    path("charges/<int:charge_id>/edit/", views.charge_edit, name="charge-edit"),
    path("charges/<int:charge_id>/delete/", views.charge_delete, name="charge-delete"),
    path("booking-logs/<int:audit_log_id>/restore/", views.booking_audit_restore, name="booking-audit-restore"),
    path("participants/<int:participant_id>/payments/new/", views.payment_create, name="payment-create"),
    path("participants/<int:participant_id>/pin/set/", views.pin_set, name="pin-set"),
    path("participants/<int:participant_id>/pin/reset/", views.pin_reset, name="pin-reset"),
    path("camps/<int:camp_id>/prices/", views.price_rules_manage, name="price-rules-manage"),
    path("camps/<int:camp_id>/prices/new/", views.price_rule_create, name="price-rule-create"),
    path("prices/<int:price_rule_id>/edit/", views.price_rule_edit, name="price-rule-edit"),
    path("camps/<int:camp_id>/expenses/new/", views.expense_create, name="expense-create"),
    path("camps/<int:camp_id>/import/", views.participant_import, name="participant-import"),
    path("camps/<int:camp_id>/export/settlements.csv", views.export_settlements_csv, name="export-settlements-csv"),
    path("camps/<int:camp_id>/export/drinks.csv", views.export_drinks_csv, name="export-drinks-csv"),
    path("camps/<int:camp_id>/export/workbook.xlsx", views.export_workbook, name="export-workbook"),
    path(
        "participants/<int:participant_id>/export/settlement.pdf",
        views.export_participant_pdf,
        name="export-participant-pdf",
    ),
    path("kiosk/", views.kiosk_home, name="kiosk-home"),
    path("kiosk/login/", views.kiosk_login, name="kiosk-login"),
    path("kiosk/pin/", views.kiosk_pin_setup, name="kiosk-pin-setup"),
    path("kiosk/logout/", views.kiosk_logout, name="kiosk-logout"),
]
