from django.urls import path

from . import views

urlpatterns = [
    path("setup/", views.setup_first_admin, name="setup"),
    path("users/", views.user_list, name="user-list"),
    path("users/new/", views.user_create, name="user-create"),
    path("users/<int:user_id>/edit/", views.user_edit, name="user-edit"),
    path("users/<int:user_id>/password/", views.user_password_reset, name="user-password-reset"),
    path("deployment/update/", views.deployment_update, name="deployment-update"),
    path("deployment/update/check/", views.deployment_update_check, name="deployment-update-check"),
    path("deployment/update/install/", views.deployment_update_install, name="deployment-update-install"),
    path("help/", views.user_guide, name="user-guide"),
    path("help/admin/", views.admin_guide, name="admin-guide"),
    path("", views.kiosk_home, name="kiosk-root"),
    path("camps/", views.camp_list, name="camp-list"),
    path("camps/new/", views.camp_create, name="camp-create"),
    path("camps/<int:camp_id>/", views.camp_detail, name="camp-detail"),
    path("camps/<int:camp_id>/edit/", views.camp_edit, name="camp-edit"),
    path("camps/<int:camp_id>/meals/", views.camp_meal_overview, name="camp-meal-overview"),
    path("camps/<int:camp_id>/meals/cutoff/", views.meal_cutoff_edit, name="meal-cutoff-edit"),
    path("camps/<int:camp_id>/meals/order-sent/", views.meal_order_mark_sent, name="meal-order-mark-sent"),
    path("camps/<int:camp_id>/participants/new/", views.participant_create, name="participant-create"),
    path("participants/<int:participant_id>/", views.participant_detail, name="participant-detail"),
    path("participants/<int:participant_id>/edit/", views.participant_edit, name="participant-edit"),
    path("participants/<int:participant_id>/archive/", views.participant_archive, name="participant-archive"),
    path("participants/<int:participant_id>/restore/", views.participant_restore, name="participant-restore"),
    path("camps/<int:camp_id>/settlements/runs/new/", views.settlement_run_create, name="settlement-run-create"),
    path("settlements/runs/<int:run_id>/", views.settlement_run_detail, name="settlement-run-detail"),
    path("settlements/runs/<int:run_id>/export.csv", views.settlement_run_export_csv, name="settlement-run-csv"),
    path(
        "settlements/runs/<int:run_id>/export.xlsx",
        views.settlement_run_export_workbook,
        name="settlement-run-workbook",
    ),
    path(
        "settlements/<int:settlement_id>/export.pdf",
        views.settlement_snapshot_export_pdf,
        name="settlement-snapshot-pdf",
    ),
    path("participants/<int:participant_id>/charges/new/", views.charge_create, name="charge-create"),
    path("charges/<int:charge_id>/edit/", views.charge_edit, name="charge-edit"),
    path("charges/<int:charge_id>/delete/", views.charge_delete, name="charge-delete"),
    path("booking-logs/<int:audit_log_id>/restore/", views.booking_audit_restore, name="booking-audit-restore"),
    path("participants/<int:participant_id>/payments/new/", views.payment_create, name="payment-create"),
    path("participants/<int:participant_id>/pin/set/", views.pin_set, name="pin-set"),
    path("participants/<int:participant_id>/pin/reset/", views.pin_reset, name="pin-reset"),
    path("camps/<int:camp_id>/prices/", views.price_rules_manage, name="price-rules-manage"),
    path("camps/<int:camp_id>/prices/new/", views.price_rule_create, name="price-rule-create"),
    path("prices/<int:price_rule_id>/edit/", views.price_rule_edit, name="price-rule-edit"),
    path("prices/<int:price_rule_id>/delete/", views.price_rule_delete, name="price-rule-delete"),
    path("camps/<int:camp_id>/shifts/", views.shift_manage, name="shift-manage"),
    path("camps/<int:camp_id>/shifts/new/", views.shift_create, name="shift-create"),
    path("camps/<int:camp_id>/shifts/report/", views.shift_report, name="shift-report"),
    path("camps/<int:camp_id>/shift-templates/", views.shift_templates_manage, name="shift-templates-manage"),
    path("camps/<int:camp_id>/shift-templates/new/", views.shift_template_create, name="shift-template-create"),
    path(
        "camps/<int:camp_id>/shift-templates/generate/", views.shift_templates_generate, name="shift-templates-generate"
    ),
    path("shift-templates/<int:template_id>/edit/", views.shift_template_edit, name="shift-template-edit"),
    path("shifts/<int:shift_id>/edit/", views.shift_edit, name="shift-edit"),
    path("shifts/<int:shift_id>/delete/", views.shift_delete, name="shift-delete"),
    path("camps/<int:camp_id>/expenses/new/", views.expense_create, name="expense-create"),
    path("expenses/<int:expense_id>/approve/", views.shared_expense_approve, name="shared-expense-approve"),
    path("expenses/<int:expense_id>/reject/", views.shared_expense_reject, name="shared-expense-reject"),
    path("camps/<int:camp_id>/import/", views.participant_import, name="participant-import"),
    path(
        "camps/<int:camp_id>/import/template/",
        views.participant_import_template_view,
        name="participant-import-template",
    ),
    path("camps/<int:camp_id>/export/settlements.csv", views.export_settlements_csv, name="export-settlements-csv"),
    path("camps/<int:camp_id>/export/drinks.csv", views.export_drinks_csv, name="export-drinks-csv"),
    path("camps/<int:camp_id>/export/workbook.xlsx", views.export_workbook, name="export-workbook"),
    path(
        "participants/<int:participant_id>/export/settlement.pdf",
        views.export_participant_pdf,
        name="export-participant-pdf",
    ),
    path("kiosk/", views.kiosk_home, name="kiosk-home"),
    path("kiosk/login/", views.kiosk_login, name="kiosk-login"),
    path("kiosk/shifts/", views.kiosk_shifts, name="kiosk-shifts"),
    path("kiosk/shared-expenses/request/", views.kiosk_shared_expense_request, name="kiosk-shared-expense-request"),
    path("kiosk/pin/", views.kiosk_pin_setup, name="kiosk-pin-setup"),
    path("kiosk/logout/", views.kiosk_logout, name="kiosk-logout"),
]
