name: Deploy to Portainer with Self-Hosted Runner

on:
  push:
    branches:
      - main  # Setzen Sie hier den Namen Ihres Haupt-Branches ein

jobs:
  deploy:
    runs-on: hetzner  # Verwenden Sie den selbst gehosteten Runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.CONTAINER_NAME }}:latest .

    - name: Push Docker image to Registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.CONTAINER_NAME }}:latest

    - name: Deploy to Portainer
      run: |
        curl -X POST "http:/${{ secrets.PORTAINER_IP }}/api/endpoints/1/docker/containers/create?name=${{ secrets.CONTAINER_NAME }}" \
             -H "Authorization: ${{ secrets.PORTAINER_API_TOKEN }}" \
             -H "Content-Type: application/json" \
             -d '{
                   "Image": "${{ secrets.DOCKER_USERNAME }}/${{ secrets.CONTAINER_NAME }}:latest",
                   "HostConfig": {
                     "PortBindings": { "5000/tcp": [{ "HostPort": "5000" }] }
                   }
                 }'
